import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f2f2f2]">
        <header>
                  <nav className="bg-white p-2 border-b border-b-[#dddddd] flex justify-between fixed w-full px-5">
                    <div>
                      <Image src="/Logo.png" alt="Logo image" width={100} height={35}/>
                    </div>
                    <div className="flex items-center gap-4">
                      <Image src="/avatar.png" alt="Logo image" width={40} height={40} className="rounded-full"/>
                      
                      <h4 className="font-semibold uppercase tracking-[.1rem]">Admin</h4>
                    </div>
                  </nav>
                </header>
        
                <div className="flex pt-13" style={{ height: '100vh' }}>
                  <nav className="w-50 border-r border-r-[#dddddd] flex flex-col justify-between p-4 bg-white ">
                    <ul className="flex flex-col gap-1">
                      <li className="bg-black w-fit py-2 px-4 text-white rounded">Dashboard</li>
                      <li className="w-fit py-2 px-4 rounded">Projects</li>
                      <li className="w-fit py-2 px-4 rounded">Managers</li>
                      <li className="w-fit py-2 px-4 rounded">Managers Report</li>
                      <li className="w-fit py-2 px-4 rounded">Employees</li>
                      <li className="w-fit py-2 px-4 rounded">Messenger</li>
                      <li className="w-fit py-2 px-4 rounded">Paylips</li>
                      <li className="w-fit py-2 px-4 rounded">Mail</li>
                    </ul>
                    <button className="py-2 mx-2 border mb-2">LogOut</button>
                  </nav>
        
        
                  <main className="flex-1 p-6 overflow-auto">
                    {children}
                  </main>
                </div>
      </body>
    </html>
  );
}
